#zf210525.1403
#source: https://hub.docker.com/r/dperson/samba

version: '3.3'

services:
    samba:
        image: dperson/samba:latest
        container_name: samba
        volumes:
            - $PWD/smb_share:/share
        restart: always
        # environment:
        #     SHARED_DIRECTORY: /nfsshare
        ports:
            - "139:139"
            - "445:445"
        # privileged: true
        command:
            -p
            -u "toto;tototutu."
            -s "toto2;/share;no;no;no;toto"
